server:
  port: 9090

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/smss?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

#整合mybatis
mybatis:
  type-aliases-package: com.smss.model
  mapper-locations: classpath:mybatis/mapper/*.xml






